// categories.ts

/**
 * Ad categories and their corresponding Kijiji categoryId values
 */
export const categories = {
    id: 0,
    BUY_AND_SELL: {
        id: 10,
        ARTS_AND_COLLECTIBLES: { id: 12 },
        AUDIO: {
            id: 767,
            IPODS_AND_MP3S: { id: 768 },
            IPOD_AND_MP3_ACCESSORIES: { id: 769 },
            HEADPHONES: { id: 770 },
            SPEAKERS: { id: 14922002 },
            STEREO_SYSTEMS_AND_HOME_THEATRE: { id: 14922001 },
            OTHER: { id: 771 }
        },
        BABY_ITEMS: {
            id: 253,
            BATHING_AND_CHANGING: { id: 272 },
            CLOTHING_PREEMIE: { id: 257 },
            CLOTHING_0_TO_3_MONTHS: { id: 258 },
            CLOTHING_3_TO_6_MONTHS: { id: 259 },
            CLOTHING_6_TO_9_MONTHS: { id: 260 },
            CLOTHING_9_TO_12_MONTHS: { id: 261 },
            CLOTHING_12_TO_18_MONTHS: { id: 262 },
            CLOTHING_18_TO_24_MONTHS: { id: 263 },
            CLOTHING_2T: { id: 264 },
            CLOTHING_3T: { id: 265 },
            CLOTHING_4T: { id: 266 },
            CLOTHING_5T: { id: 267 },
            CRIBS: { id: 269 },
            FEEDING_AND_HIGH_CHAIRS: { id: 271 },
            GATES_MONITORS_AND_SAFETY: { id: 273 },
            PLAYPENS_SWINGS_AND_SAUCERS: { id: 268 },
            STROLLERS_CARRIERS_AND_CAR_SEATS: { id: 270 },
            TOYS: { id: 256 },
            MULTI_ITEM: { id: 255 },
            OTHER: { id: 254 }
        },
        BIKES: {
            id: 644,
            BMX: { id: 645 },
            CLOTHING_SHOES_AND_ACCESSORIES: { id: 650 },
            CRUISER_COMMUTER_AND_HYBRID: { id: 15096001 },
            EBIKE: { id: 14654001 },
            FIXIE_SINGLE_SPEED: { id: 15096002 },
            FRAMES_AND_PARTS: { id: 649 },
            KIDS: { id: 646 },
            MOUNTAIN: { id: 647 },
            ROAD: { id: 648 },
            OTHER: { id: 651 }
        },
        BOOKS: {
            id: 109,
            TEXTBOOKS: { id: 14970001 },
            MAGAZINES: { id: 14970002 },
            CHILDREN_AND_YOUNG_ADULT: { id: 14970003 },
            COMICS_AND_GRAPHIC_NOVELS: { id: 14970004 },
            FICTION: { id: 14970005 },
            NON_FICTION: { id: 14970006 },
            OTHER: { id: 14970007 }
        },
        BUSINESS_AND_INDUSTRIAL: {
            id: 29659003,
            INDUSTRIAL_KITCHEN_SUPPLIES: { id: 29659004 },
            INDUSTRIAL_SHELVING_AND_RACKING: { id: 29659005 },
            STORAGE_CONTAINERS: { id: 29659006 },
            OTHER_BUSINESS_AND_INDUSTRIAL: { id: 145 }
        },
        CAMERAS_AND_CAMCORDERS: { id: 103 },
        CDS_DVDS_AND_BLU_RAY: { id: 104 },
        CLOTHING: {
            id: 274,
            COSTUMES: { id: 277 },
            KIDS_AND_YOUTH: { id: 279 },
            MENS: { id: 278 },
            MENS_SHOES: { id: 15117001 },
            MULTI_ITEM: { id: 276 },
            WEDDING: { id: 280 },
            WOMENS_BAGS_AND_WALLETS: { id: 281 },
            WOMENS_BOTTOMS: { id: 285 },
            WOMENS_DRESSES_AND_SKIRTS: { id: 283 },
            WOMENS_MATERNITY: { id: 282 },
            WOMENS_SHOES: { id: 286 },
            WOMENS_TOPS_AND_OUTERWEAR: { id: 284 },
            OTHER: { id: 275 },
            WOMENS_OTHER: { id: 287 }
        },
        COMPUTERS: {
            id: 16,
            DESKTOP_COMPUTERS: { id: 772 },
            IPADS_AND_TABLETS: { id: 776 },
            LAPTOPS: { id: 773 },
            SERVERS: { id: 774 },
            OTHER: { id: 29324001 }
        },
        COMPUTER_ACCESSORIES: {
            id: 128,
            CABLES_AND_CONNECTORS: { id: 777 },
            FLASH_MEMORY_AND_USB_STICKS: { id: 778 },
            IPAD_AND_TABLET_ACCESSORIES: { id: 789 },
            LAPTOP_ACCESSORIES: { id: 780 },
            MICE_KEYBOARDS_AND_WEBCAMS: { id: 781 },
            MONITORS: { id: 782 },
            NETWORKING: { id: 783 },
            PRINTERS_SCANNERS_AND_FAX: { id: 784 },
            SERVICES_TRAINING_AND_REPAIR: { id: 785 },
            SOFTWARE: { id: 786 },
            SPEAKERS_HEADSETS_AND_MICS: { id: 787 },
            SYSTEM_COMPONENTS: { id: 788 },
            OTHER: { id: 790 }
        },
        ELECTRONICS: {
            id: 29659001,
            GENERAL_ELECTRONICS: { id: 15 },
            SECURITY_SYSTEMS: { id: 29659002 }
        },
        FREE_STUFF: { id: 17220001 },
        FURNITURE: {
            id: 235,
            BEDS_AND_MATTRESSES: { id: 246 },
            BOOKCASES_AND_SHELVING_UNITS: { id: 249 },
            CHAIRS_AND_RECLINERS: { id: 245 },
            COFFEE_TABLES: { id: 241 },
            COUCHES_AND_FUTONS: { id: 238 },
            DESKS: { id: 239 },
            DINING_TABLES_AND_SETS: { id: 243 },
            DRESSERS_AND_WARDROBES: { id: 247 },
            HUTCHES_AND_DISPLAY_CABINETS: { id: 250 },
            OTHER_TABLES: { id: 244 },
            TV_TABLES_AND_ENTERTAINMENT_UNITS: { id: 242 },
            MULTI_ITEM: { id: 237 },
            OTHER: { id: 236 }
        },
        GARAGE_SALES: { id: 638 },
        HEALTH_AND_SPECIAL_NEEDS: { id: 140 },
        HOBBIES_AND_CRAFTS: { id: 139 },
        HOME_APPLIANCES: {
            id: 107,
            COFFEE_MAKERS: { id: 689 },
            DISHWASHERS: { id: 690 },
            FREEZERS: { id: 691 },
            HEATERS_HUMIDIFIERS_AND_DEHUMIDIFIERS: { id: 692 },
            IRONS_AND_GARMENT_STEAMERS: { id: 693 },
            MICROWAVES_AND_COOKERS: { id: 694 },
            PROCESSORS_BLENDERS_AND_JUICERS: { id: 695 },
            REFRIGERATORS: { id: 696 },
            STOVES_OVENS_AND_RANGES: { id: 697 },
            TOASTERS_AND_TOASTER_OVENS: { id: 698 },
            VACUUMS: { id: 699 },
            WASHERS_AND_DRYERS: { id: 700 },
            OTHER: { id: 701 }
        },
        HOME_INDOOR: {
            id: 717,
            BATHWARES: { id: 718 },
            BEDDING: { id: 719 },
            FIREPLACE_AND_FIREWOOD: { id: 15058001 },
            HOLIDAY_EVENT_AND_SEASONAL: { id: 15058002 },
            HOME_DECOR_AND_ACCENTS: { id: 720 },
            INDOOR_LIGHTING_AND_FANS: { id: 721 },
            KITCHEN_AND_DINING_WARES: { id: 722 },
            RUGS_CARPETS_AND_RUNNERS: { id: 723 },
            STORAGE_AND_ORGANIZATION: { id: 15058003 },
            WINDOW_TREATMENTS: { id: 724 },
            OTHER: { id: 725 }
        },
        HOME_OUTDOOR_AND_GARDEN: {
            id: 19,
            BBQS_AND_OUTDOOR_COOKING: { id: 678 },
            DECKS_AND_FENCES: { id: 679 },
            GARAGE_DOORS_AND_OPENERS: { id: 680 },
            HOT_TUBS_AND_POOLS: { id: 681 },
            LAWNMOWERS_AND_LEAF_BLOWERS: { id: 682 },
            OUTDOOR_DECOR: { id: 683 },
            OUTDOOR_LIGHTING: { id: 684 },
            OUTDOOR_TOOLS_AND_STORAGE: { id: 685 },
            PATIO_AND_GARDEN_FURNITURE: { id: 686 },
            PLANTS_FERTILIZER_AND_SOIL: { id: 687 },
            SNOWBLOWERS: { id: 688 },
            OTHER: { id: 726 }
        },
        HOME_RENOVATION_MATERIALS: {
            id: 727,
            CABINETS_AND_COUNTERTOPS: { id: 728 },
            ELECTRICAL: { id: 729 },
            FLOORS_AND_WALLS: { id: 730 },
            HARDWARE_NAILS_AND_SCREWS: { id: 731 },
            HEATING_COOLING_AND_AIR: { id: 732 },
            PAINTING_AND_PAINT_SUPPLIES: { id: 733 },
            PLUMBING_SINKS_TOILETS_AND_SHOWERS: { id: 734 },
            ROOFING: { id: 735 },
            WINDOWS_DOORS_AND_TRIM: { id: 736 },
            OTHER: { id: 737 }
        },
        JEWELLERY_AND_WATCHES: { id: 133 },
        MUSICAL_INSTRUMENTS: {
            id: 17,
            AMPS_AND_PEDALS: { id: 610 },
            BRASS: { id: 611 },
            DRUMS_AND_PERCUSSION: { id: 612 },
            GUITARS: { id: 613 },
            PERFORMANCE_AND_DJ_EQUIPMENT: { id: 14922003 },
            PIANOS_AND_KEYBOARDS: { id: 614 },
            PRO_AUDIO_AND_RECORDING_EQUIPMENT: { id: 615 },
            STRING: { id: 616 },
            WOODWIND: { id: 617 },
            OTHER: { id: 618 }
        },
        PHONES: {
            id: 132,
            CELL_PHONES: { id: 760 },
            CELL_PHONE_ACCESSORIES: { id: 761 },
            CELL_PHONE_SERVICES: { id: 762 },
            HOME_PHONES_AND_ANSWERING_MACHINES: { id: 765 },
            OTHER: { id: 766 }
        },
        SPORTING_GOODS_AND_EXERCISE: {
            id: 111,
            BASEBALL_AND_SOFTBALL: { id: 652 },
            BASKETBALL: { id: 653 },
            CURLING: { id: 654 },
            EXERCISE_EQUIPMENT: { id: 655 },
            FISHING_CAMPING_AND_OUTDOORS: { id: 656 },
            FOOTBALL: { id: 657 },
            GOLF: { id: 658 },
            HOCKEY: { id: 659 },
            LACROSSE: { id: 660 },
            PAINTBALL: { id: 661 },
            SKATES_AND_BLADES: { id: 662 },
            SKATEBOARD: { id: 663 },
            SKI: { id: 664 },
            SNOWBOARD: { id: 665 },
            SOCCER: { id: 666 },
            TENNIS_AND_RACQUET: { id: 667 },
            WATER_SPORTS: { id: 668 },
            OTHER: { id: 669 }
        },
        TOOLS: {
            id: 110,
            HAND_TOOLS: { id: 702 },
            POWER_TOOLS: { id: 703 },
            TOOL_STORAGE_AND_BENCHES: { id: 704 },
            LADDERS_AND_SCAFFOLDING: { id: 705 },
            OTHER: { id: 715 }
        },
        TOYS_AND_GAMES: { id: 108 },
        TVS_AND_VIDEO: {
            id: 15093001,
            TVS: { id: 15093002 },
            VIDEO_AND_TV_ACCESSORIES: { id: 15093003 }
        },
        VIDEO_GAMES_AND_CONSOLES: {
            id: 141,
            NINTENDO_DS: { id: 619 },
            NINTENDO_SWITCH: { id: 33035001 },
            NINTENDO_WII: { id: 626 },
            NINTENDO_WII_U: { id: 14654002 },
            SONY_PLAYSTATION_5: { id: 39730002 },
            SONY_PLAYSTATION_4: { id: 792 },
            SONY_PLAYSTATION_3: { id: 627 },
            SONY_PSP_AND_VITA: { id: 621 },
            XBOX_SERIES_X_AND_S: { id: 39730001 },
            XBOX_360: { id: 622 },
            XBOX_ONE: { id: 793 },
            OLDER_GENERATION: { id: 623 },
            PC_GAMES: { id: 624 },
            OTHER: { id: 625 }
        },
        OTHER: { id: 26 }
    },
    CARS_AND_VEHICLES: {
        id: 27,
        CARS_AND_TRUCKS: { id: 174 },
        CLASSIC_CARS: { id: 122 },
        VEHICLE_PARTS_TIRES_AND_ACCESSORIES: {
            id: 31,
            AUDIO_AND_GPS: { id: 316 },
            ATV_PARTS_TRAILERS_AND_ACCESSORIES: { id: 312 },
            AUTO_BODY_PARTS: { id: 317 },
            ENGINE_AND_ENGINE_PARTS: { id: 318 },
            HEAVY_EQUIPMENT_PARTS_AND_ACCESSORIES: { id: 342 },
            SNOWMOBILES_PARTS_TRAILERS_AND_ACCESSORIES: { id: 314 },
            TIRES_AND_RIMS: { id: 320 },
            BOAT_PARTS_TRAILERS_AND_ACCESSORIES: { id: 331 },
            RV_AND_CAMPER_PARTS_AND_ACCESSORIES: { id: 337 },
            TRANSMISSION_AND_DRIVETRAIN: { id: 319 },
            OTHER_PARTS_AND_ACCESSORIES: { id: 321 },
            MOTORCYCLE_PARTS_AND_ACCESSORIES: { id: 309 }
        },
        AUTOMOTIVE_SERVICES: {
            id: 142,
            AUTO_INSURANCE_AND_FINANCING: { id: 325 },
            DETAILING_AND_CLEANING: { id: 323 },
            REPAIRS_AND_MAINTENANCE: { id: 322 },
            TOWING_AND_SCRAP_REMOVAL: { id: 324 },
            OTHER: { id: 326 }
        },
        MOTORCYCLES: {
            id: 30,
            DIRT_BIKES_AND_MOTOCROSS: { id: 307 },
            SCOOTERS_AND_POCKET_BIKES: { id: 308 },
            SPORT_BIKES: { id: 304 },
            SPORT_TOURING: { id: 305 },
            STREET_CRUISERS_AND_CHOPPERS: { id: 303 },
            TOURING: { id: 306 },
            OTHER: { id: 310 }
        },
        ATVS_AND_SNOWMOBILES: {
            id: 171,
            ATVS: { id: 311 },
            SNOWMOBILES: { id: 313 },
            OTHER: { id: 315 }
        },
        BOATS_AND_WATERCRAFT: {
            id: 29,
            CANOES_KAYAKS_AND_PADDLES: { id: 329 },
            POWERBOATS_AND_MOTORBOATS: { id: 327 },
            SAILBOATS: { id: 328 },
            PERSONAL_WATERCRAFT: { id: 330 },
            OTHER: { id: 332 }
        },
        RVS_CAMPERS_AND_TRAILERS: {
            id: 172,
            CARGO_AND_UTILITY_TRAILERS: { id: 336 },
            PARK_MODELS: { id: 335 },
            RVS_AND_MOTORHOMES: { id: 333 },
            TRAVEL_TRAILERS_AND_CAMPERS: { id: 334 },
            OTHER: { id: 338 }
        },
        HEAVY_EQUIPMENT: {
            id: 301,
            FARMING_EQUIPMENT: { id: 341 },
            HEAVY_EQUIPMENT: { id: 340 },
            HEAVY_TRUCKS: { id: 339 },
            OTHER: { id: 343 }
        },
        OTHER: { id: 33 }
    },
    REAL_ESTATE: {
        id: 34,
        FOR_RENT: {
            id: 30349001,
            LONG_TERM_RENTALS: { id: 37 },
            SHORT_TERM_RENTALS: { id: 42 },
            ROOM_RENTALS_AND_ROOMMATES: { id: 36 },
            STORAGE_AND_PARKING_FOR_RENT: { id: 39 },
            COMMERCIAL_AND_OFFICE_SPACE_FOR_RENT: { id: 40 }
        },
        FOR_SALE: {
            id: 30353001,
            HOUSES_FOR_SALE: { id: 35 },
            CONDOS_FOR_SALE: { id: 643 },
            LAND_FOR_SALE: { id: 641 },
            COMMERCIAL_AND_OFFICE_SPACE_FOR_SALE: { id: 44 }
        },
        REAL_ESTATE_SERVICES: { id: 170 }
    },
    JOBS: {
        id: 45,
        ACCOUNTING_AND_MANAGEMENT: { id: 58 },
        CHILD_CARE: { id: 47 },
        BAR_FOOD_AND_HOSPITALITY: { id: 60 },
        CLEANING_AND_HOUSEKEEPING: { id: 146 },
        CONSTRUCTION_AND_TRADES: { id: 50 },
        CUSTOMER_SERVICE: { id: 147 },
        CANNABIS_SECTOR: { id: 420 },
        DRIVERS_AND_SECURITY: { id: 148 },
        GENERAL_LABOUR: { id: 149 },
        GRAPHIC_AND_WEB_DESIGN: { id: 152 },
        HEALTHCARE: { id: 898 },
        HAIR_STYLIST_AND_SALON: { id: 150 },
        OFFICE_MANAGER_AND_RECEPTIONIST: { id: 46 },
        PART_TIME_AND_STUDENTS: { id: 59 },
        PROGRAMMERS_AND_COMPUTER: { id: 54 },
        SALES_AND_RETAIL_SALES: { id: 61 },
        TV_MEDIA_AND_FASHION: { id: 55 },
        OTHER: { id: 62 }
    },
    SERVICES: {
        id: 72,
        CHILDCARE_AND_NANNY: { id: 84 },
        CLEANERS_AND_CLEANING: { id: 160 },
        ENTERTAINMENT: { id: 165 },
        FINANCIAL_AND_LEGAL: { id: 131 },
        FITNESS_AND_PERSONAL_TRAINER: { id: 83 },
        FOOD_AND_CATERING: { id: 15214001 },
        HEALTH_AND_BEAUTY: { id: 166 },
        MOVING_AND_STORAGE: { id: 144 },
        MUSIC_LESSONS: { id: 86 },
        PHOTOGRAPHY_AND_VIDEO: { id: 168 },
        SKILLED_TRADES: {
            id: 76,
            APPLIANCE_REPAIR_AND_INSTALLATION: { id: 738 },
            BRICK_MASONRY_AND_CONCRETE: { id: 739 },
            CARPENTRY_CROWN_MOULDING_AND_TRIMWORK: { id: 740 },
            DRYWALL_AND_STUCCO_REMOVAL: { id: 741 },
            ELECTRICIAN: { id: 742 },
            EXCAVATION_DEMOLITION_AND_WATERPROOFING: { id: 743 },
            FENCE_DECK_RAILING_AND_SIDING: { id: 744 },
            FLOORING: { id: 745 },
            GARAGE_DOOR: { id: 746 },
            HEATING_VENTILATION_AND_AIR_CONDITIONING: { id: 747 },
            INSULATION: { id: 748 },
            INTERLOCK_PAVING_AND_DRIVEWAYS: { id: 749 },
            LAWN_TREE_MAINTENANCE_AND_EAVESTROUGH: { id: 750 },
            PAINTERS_AND_PAINTING: { id: 759 },
            PHONE_NETWORK_CABLE_AND_HOME_WIRING: { id: 751 },
            PLUMBING: { id: 752 },
            RENOVATIONS_GENERAL_CONTRACTING_AND_HANDYMAN: { id: 753 },
            ROOFING: { id: 754 },
            SNOW_REMOVAL_AND_PROPERTY_MAINTENANCE: { id: 755 },
            WELDING: { id: 756 },
            WINDOWS_AND_DOORS: { id: 757 },
            OTHER: { id: 758 }
        },
        TUTORS_AND_LANGUAGES: { id: 169 },
        WEDDING: { id: 79 },
        TRAVEL_AND_VACATIONS: { id: 302 },
        OTHER: { id: 87 }
    },
    PETS: {
        id: 112,
        ANIMAL_AND_PET_SERVICES: { id: 143 },
        BIRDS_FOR_REHOMING: { id: 135 },
        CATS_AND_KITTENS_FOR_REHOMING: { id: 125 },
        DOGS_AND_PUPPIES_FOR_REHOMING: { id: 126 },
        EQUESTRIAN_AND_LIVESTOCK_ACCESSORIES: { id: 14996002 },
        FISH_FOR_REHOMING: { id: 14654003 },
        HORSES_AND_PONIES_FOR_REHOMING: { id: 14996001 },
        LIVESTOCK: { id: 217 },
        LOST_AND_FOUND: { id: 791 },
        ACCESSORIES: { id: 115 },
        REPTILES_AND_AMPHIBIANS_FOR_REHOMING: { id: 14654004 },
        SMALL_ANIMALS_FOR_REHOMING: { id: 14654005 },
        OTHER_PETS_FOR_REHOMING: { id: 114 },
        OTHER: { id: 127 }
    },
    COMMUNITY: {
        id: 1,
        ACTIVITIES_AND_GROUPS: { id: 7 },
        ARTISTS_AND_MUSICIANS: { id: 2 },
        CLASSES_AND_LESSONS: { id: 4 },
        EVENTS: { id: 289 },
        FRIENDSHIP_AND_NETWORKING: { id: 634 },
        LONG_LOST_RELATIONSHIPS: { id: 635 },
        LOST_AND_FOUND: { id: 120 },
        MISSED_CONNECTIONS: { id: 636 },
        RIDESHARE: { id: 5 },
        SPORTS_TEAMS: { id: 15102001 },
        VOLUNTEERS: { id: 3 },
        OTHER: { id: 9 }
    },
    VACATION_RENTALS: {
        id: 800,
        CANADA: {
            id: 801,
            ALBERTA: { id: 806 },
            BRITISH_COLUMBIA: { id: 807 },
            MANITOBA: { id: 808 },
            NEW_BRUNSWICK: { id: 809 },
            NEWFOUNDLAND_AND_LABRADOR: { id: 810 },
            NOVA_SCOTIA: { id: 811 },
            ONTARIO: { id: 812 },
            PRINCE_EDWARD_ISLAND: { id: 813 },
            QUEBEC: { id: 814 },
            SASKATCHEWAN: { id: 815 },
            OTHER_CANADA: { id: 816 }
        },
        USA: {
            id: 802,
            ALABAMA: { id: 817 },
            ALASKA: { id: 818 },
            ARIZONA: { id: 819 },
            ARKANSAS: { id: 820 },
            CALIFORNIA: { id: 821 },
            COLORADO: { id: 822 },
            CONNECTICUT: { id: 823 },
            DELAWARE: { id: 824 },
            FLORIDA: { id: 825 },
            GEORGIA: { id: 826 },
            HAWAII: { id: 827 },
            IDAHO: { id: 828 },
            ILLINOIS: { id: 829 },
            INDIANA: { id: 830 },
            IOWA: { id: 831 },
            KANSAS: { id: 832 },
            KENTUCKY: { id: 833 },
            LOUISIANA: { id: 834 },
            MAINE: { id: 835 },
            MARYLAND: { id: 836 },
            MASSACHUSETTS: { id: 837 },
            MICHIGAN: { id: 838 },
            MINNESOTA: { id: 839 },
            MISSISSIPPI: { id: 840 },
            MISSOURI: { id: 841 },
            MONTANA: { id: 842 },
            NEBRASKA: { id: 843 },
            NEVADA: { id: 844 },
            NEW_HAMPSHIRE: { id: 845 },
            NEW_JERSEY: { id: 846 },
            NEW_MEXICO: { id: 847 },
            NEW_YORK: { id: 848 },
            NORTH_CAROLINA: { id: 849 },
            NORTH_DAKOTA: { id: 850 },
            OHIO: { id: 851 },
            OKLAHOMA: { id: 852 },
            OREGON: { id: 853 },
            PENNSYLVANIA: { id: 854 },
            RHODE_ISLAND: { id: 855 },
            SOUTH_CAROLINA: { id: 856 },
            SOUTH_DAKOTA: { id: 857 },
            TENNESSEE: { id: 858 },
            TEXAS: { id: 859 },
            UTAH: { id: 860 },
            VERMONT: { id: 861 },
            VIRGINIA: { id: 862 },
            WASHINGTON: { id: 863 },
            WASHINGTON_DC: { id: 864 },
            WEST_VIRGINIA: { id: 865 },
            WISCONSIN: { id: 866 },
            WYOMING: { id: 867 },
            OTHER_UNITED_STATES: { id: 868 }
        },
        CARIBBEAN: {
            id: 803,
            ANGUILLA: { id: 869 },
            ANTIGUA_AND_BARBUDA: { id: 870 },
            ARUBA: { id: 871 },
            BAHAMAS: { id: 872 },
            BARBADOS: { id: 873 },
            BAY_ISLANDS: { id: 874 },
            BONAIRE: { id: 875 },
            CAYMAN_ISLANDS: { id: 876 },
            CUBA: { id: 877 },
            CURACAO: { id: 878 },
            DOMINIQUE: { id: 879 },
            DOMINICAN_REPUBLIC: { id: 880 },
            GRENADA: { id: 881 },
            GUADELOUPE: { id: 882 },
            JAMAICA: { id: 883 },
            MARGARITA_ISLAND: { id: 884 },
            MARTINIQUE: { id: 885 },
            MONTSERRAT: { id: 886 },
            PUERTO_RICO: { id: 887 },
            SABA: { id: 888 },
            SAN_ANDRES_PROVIDENCIA: { id: 889 },
            ST_BARTHELEMY: { id: 890 },
            ST_KITTS_AND_NEVIS: { id: 891 },
            ST_LUCIA: { id: 892 },
            ST_MAARTEN_ST_MARTIN: { id: 893 },
            TRINIDAD_AND_TOBAGO: { id: 894 },
            TURKS_AND_CAICOS: { id: 895 },
            VIRGIN_ISLANDS: { id: 896 },
            OTHER_CARIBBEAN: { id: 897 }
        },
        MEXICO: { id: 804 },
        OTHER_COUNTRIES: { id: 805 }
    }
};
